{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubevuln.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.kubevuln.name }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubevuln.name "tier" .Values.global.namespaceTier) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubevuln.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.kubevuln.name }}
  namespace: {{ .Values.ksNamespace }}
{{- end }}
