apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/kubescape/charts/kubescape-operator
  contents:
  - path: .
    git:
      url: https://github.com/kubescape/helm-charts
      ref: kubescape-operator-1.28.0
    includePaths:
      - charts/kubescape-operator/**
    newRootPath: charts/kubescape-operator